io.bitnet.model.payer.payer.Address:
  - field: addressLine1
  - field: addressLine2
  - field: city
  - field: postalCode
  - field: country
  - field: region
io.bitnet.model.payment.order.Address:
  - field: addressLine1
  - field: addressLine2
  - field: city
  - field: postalCode
  - field: country
  - field: region